class InternalError(Exception):
    """Custom exception class."""
    pass

class NamedError(InternalError):
    """Custom exception class."""
    pass

